version: '3.3'

services:
  react:
    build:
      context: ../BubbleTMA
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app_network

  backend:
    build:
      context: ../Backend/BubbleGame
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - app_network
  transactions:
    build:
      context: ../Backend/Transactions
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
